### ISSUE TITLE
Supported for UWP-Apps (Universelle Windows-Plattform) 

### ISSUE THREAD

**Issue by UltimateFighter** [fernandospr/java-wns#11]
Is this only for Windows 8.x or Windows Phone 8.x or it is also supported for UWP-Apps (Universelle Windows-Plattform) and Windows 10?

**Comment by fernandospr** [comment]
Hi, this is not for Windows Phone. Check java-mpns.

**Comment by charpin** [comment]
I'm curious about your answer. I'm used your library and it work like a charm on Windows Phone 8.1. My app is deploy as Windows Phone Universel and I have no problem to send et receive notifications windows. 

About Windows 10, I don't know yet. It will be interesting to make a test. I think it can be work because Microsoft advice to use WNS platform for all windows device where the minimum  target version is 8.1. 

It's not recommanded to use Java-MPNS because it's affect only the Windows Phone 8.0 and Windows Phone 8.1 Silverlight (this one use also WNS).

**Comment by fernandospr** [comment]
Hi, if your app uses WNS then this library will work ok.
However if your app uses MPNS, then this library won't work.

**Comment by nirav9261** [comment]
@charpin Hello, I am trying to get this java-wns API working for windows phone push notifications but facing issues with JSON object mapper. Have opened an issue [here ](https://github.com/fernandospr/java-wns/issues/22)with code and error trace :
https://github.com/fernandospr/java-wns/issues/22

Can you please help me out here. Thanks, Nirav
